"""autogenerated by genpy from robotnik_arduimu/Arduimu_raw.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class Arduimu_raw(genpy.Message):
  _md5sum = "4e67335249b4b6ce801af011d9186e30"
  _type = "robotnik_arduimu/Arduimu_raw"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
int32  temperature	# in ?
int32  aX		# acceleration X axis 30 = 1g = 9.81 m/s² 0.327 
int32  aY               # acceleration Y axis 
int32  aZ  	        # acceleration Z axis
int32  gX               # gyro X axis  
int32  gY               # gyro Y axis
int32  gZ               # gyro Z axis
int32  mX               # magnetometer X axis
int32  mY               # magnetometer Y axis
int32  mZ               # magnetometer Z axis


================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

"""
  __slots__ = ['header','temperature','aX','aY','aZ','gX','gY','gZ','mX','mY','mZ']
  _slot_types = ['std_msgs/Header','int32','int32','int32','int32','int32','int32','int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,temperature,aX,aY,aZ,gX,gY,gZ,mX,mY,mZ

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Arduimu_raw, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.temperature is None:
        self.temperature = 0
      if self.aX is None:
        self.aX = 0
      if self.aY is None:
        self.aY = 0
      if self.aZ is None:
        self.aZ = 0
      if self.gX is None:
        self.gX = 0
      if self.gY is None:
        self.gY = 0
      if self.gZ is None:
        self.gZ = 0
      if self.mX is None:
        self.mX = 0
      if self.mY is None:
        self.mY = 0
      if self.mZ is None:
        self.mZ = 0
    else:
      self.header = std_msgs.msg.Header()
      self.temperature = 0
      self.aX = 0
      self.aY = 0
      self.aZ = 0
      self.gX = 0
      self.gY = 0
      self.gZ = 0
      self.mX = 0
      self.mY = 0
      self.mZ = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_10i.pack(_x.temperature, _x.aX, _x.aY, _x.aZ, _x.gX, _x.gY, _x.gZ, _x.mX, _x.mY, _x.mZ))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 40
      (_x.temperature, _x.aX, _x.aY, _x.aZ, _x.gX, _x.gY, _x.gZ, _x.mX, _x.mY, _x.mZ,) = _struct_10i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_10i.pack(_x.temperature, _x.aX, _x.aY, _x.aZ, _x.gX, _x.gY, _x.gZ, _x.mX, _x.mY, _x.mZ))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 40
      (_x.temperature, _x.aX, _x.aY, _x.aZ, _x.gX, _x.gY, _x.gZ, _x.mX, _x.mY, _x.mZ,) = _struct_10i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_10i = struct.Struct("<10i")
