# Set the variables from the CMakeLists.txt files
SET(CPACK_GENERATOR "TBZ2;DEB")
SET(CPACK_PACKAGE_NAME "uvcdynctrl")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Manage dynamic controls in uvcvideo")
SET(CPACK_PACKAGE_DESCRIPTION "Command line tool to obtain and change camera controls and manage dynamic controls.")
SET(CPACK_PACKAGE_VENDOR "Logitech")
SET(CPACK_PACKAGE_VERSION "0.2.1")
SET(CPACK_PACKAGE_FILE_NAME "uvcdynctrl-0.2.1-amd64")
SET(CPACK_DEBIAN_PACKAGE_MAINTAINER "Martin Rubli <martin_rubli@logitech.com>")
SET(CPACK_DEBIAN_PACKAGE_DEPENDS "libwebcam (>= 0.2), libc6 (>= 2.7)")
SET(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "amd64")

SET(CPACK_INSTALL_PREFIX "/usr/local")
SET(CPACK_OUTPUT_CONFIG_FILE "/home/summit/Sources/summit/summit_robot/webcam-tools/uvcdynctrl/CPackConfig.cmake")
# The third argument is the component. In our case we have one component per
# project with the same name as the project. We only want to install that one
# for the packaging process, otherwise (with the default 'ALL') we would end
# up with the libwebcam files contained inside the uvcdynctrl package.
SET(CPACK_INSTALL_CMAKE_PROJECTS ".;UVCDYNCTRL;UVCDYNCTRL;/")

# These are standard and were generated by CMake
SET(CPACK_CMAKE_GENERATOR "Unix Makefiles")
SET(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
SET(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
SET(CPACK_MODULE_PATH "")
SET(CPACK_PACKAGE_DEFAULT_LOCATION "/")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-2.6/Templates/CPack.GenericDescription.txt")
SET(CPACK_RESOURCE_FILE_LICENSE "/usr/share/cmake-2.6/Templates/CPack.GenericLicense.txt")
SET(CPACK_RESOURCE_FILE_README "/usr/share/cmake-2.6/Templates/CPack.GenericDescription.txt")
SET(CPACK_RESOURCE_FILE_WELCOME "/usr/share/cmake-2.6/Templates/CPack.GenericWelcome.txt")
SET(CPACK_SET_DESTDIR "OFF")
SET(CPACK_SYSTEM_NAME "Linux")
SET(CPACK_TOPLEVEL_TAG "Linux")
