# New robot X position (mm)
float32 x
# New robot Y position (mm)
float32 y
# New robot Z position (mm)
float32 z
# New robot Orientation (grad)
float32 a
# New robot Orientation (grad)
float32 b
# New robot Orientation (grad)
float32 c
---
bool ret 
