/* Auto-generated by genmsg_cpp for file /opt/ros/fuerte/stacks/robotnik_components/robotnik_msgs/srv/set_mode.srv */
#ifndef ROBOTNIK_MSGS_SERVICE_SET_MODE_H
#define ROBOTNIK_MSGS_SERVICE_SET_MODE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace robotnik_msgs
{
template <class ContainerAllocator>
struct set_modeRequest_ {
  typedef set_modeRequest_<ContainerAllocator> Type;

  set_modeRequest_()
  : mode(0)
  {
  }

  set_modeRequest_(const ContainerAllocator& _alloc)
  : mode(0)
  {
  }

  typedef int8_t _mode_type;
  int8_t mode;


  typedef boost::shared_ptr< ::robotnik_msgs::set_modeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotnik_msgs::set_modeRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct set_modeRequest
typedef  ::robotnik_msgs::set_modeRequest_<std::allocator<void> > set_modeRequest;

typedef boost::shared_ptr< ::robotnik_msgs::set_modeRequest> set_modeRequestPtr;
typedef boost::shared_ptr< ::robotnik_msgs::set_modeRequest const> set_modeRequestConstPtr;


template <class ContainerAllocator>
struct set_modeResponse_ {
  typedef set_modeResponse_<ContainerAllocator> Type;

  set_modeResponse_()
  : ret(false)
  {
  }

  set_modeResponse_(const ContainerAllocator& _alloc)
  : ret(false)
  {
  }

  typedef uint8_t _ret_type;
  uint8_t ret;


  typedef boost::shared_ptr< ::robotnik_msgs::set_modeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotnik_msgs::set_modeResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct set_modeResponse
typedef  ::robotnik_msgs::set_modeResponse_<std::allocator<void> > set_modeResponse;

typedef boost::shared_ptr< ::robotnik_msgs::set_modeResponse> set_modeResponsePtr;
typedef boost::shared_ptr< ::robotnik_msgs::set_modeResponse const> set_modeResponseConstPtr;

struct set_mode
{

typedef set_modeRequest Request;
typedef set_modeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct set_mode
} // namespace robotnik_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::robotnik_msgs::set_modeRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::robotnik_msgs::set_modeRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::robotnik_msgs::set_modeRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "418c02483a8ca57215fb7b31c5c87234";
  }

  static const char* value(const  ::robotnik_msgs::set_modeRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x418c02483a8ca572ULL;
  static const uint64_t static_value2 = 0x15fb7b31c5c87234ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotnik_msgs::set_modeRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "robotnik_msgs/set_modeRequest";
  }

  static const char* value(const  ::robotnik_msgs::set_modeRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::robotnik_msgs::set_modeRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
int8 mode\n\
\n\
";
  }

  static const char* value(const  ::robotnik_msgs::set_modeRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::robotnik_msgs::set_modeRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::robotnik_msgs::set_modeResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::robotnik_msgs::set_modeResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::robotnik_msgs::set_modeResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e2cc9e9d8c464550830df49c160979ad";
  }

  static const char* value(const  ::robotnik_msgs::set_modeResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xe2cc9e9d8c464550ULL;
  static const uint64_t static_value2 = 0x830df49c160979adULL;
};

template<class ContainerAllocator>
struct DataType< ::robotnik_msgs::set_modeResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "robotnik_msgs/set_modeResponse";
  }

  static const char* value(const  ::robotnik_msgs::set_modeResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::robotnik_msgs::set_modeResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool ret\n\
\n\
\n\
";
  }

  static const char* value(const  ::robotnik_msgs::set_modeResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::robotnik_msgs::set_modeResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::robotnik_msgs::set_modeRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.mode);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct set_modeRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::robotnik_msgs::set_modeResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.ret);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct set_modeResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<robotnik_msgs::set_mode> {
  static const char* value() 
  {
    return "961700910d81510cfbb56c2b771e2e2f";
  }

  static const char* value(const robotnik_msgs::set_mode&) { return value(); } 
};

template<>
struct DataType<robotnik_msgs::set_mode> {
  static const char* value() 
  {
    return "robotnik_msgs/set_mode";
  }

  static const char* value(const robotnik_msgs::set_mode&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<robotnik_msgs::set_modeRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "961700910d81510cfbb56c2b771e2e2f";
  }

  static const char* value(const robotnik_msgs::set_modeRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<robotnik_msgs::set_modeRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "robotnik_msgs/set_mode";
  }

  static const char* value(const robotnik_msgs::set_modeRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<robotnik_msgs::set_modeResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "961700910d81510cfbb56c2b771e2e2f";
  }

  static const char* value(const robotnik_msgs::set_modeResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<robotnik_msgs::set_modeResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "robotnik_msgs/set_mode";
  }

  static const char* value(const robotnik_msgs::set_modeResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTNIK_MSGS_SERVICE_SET_MODE_H

