      #info: wiki.ros.org/base_local_planner
controller_frequency: 15.0
TrajectoryPlannerROS:
  max_vel_x: 0.45     #(in meters/second)
  min_vel_x: 0.1
  #max_rotational_vel: 0.5
  max_vel_theta: 0.8      #(in radians/second).
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.4   #Min rotational vel allowed for the base while performing in-place rotations.
  escape_vel: -0.25

  acc_lim_x: 0.7          #(in meters per squared second)
  acc_lim_y: 1.0          #(meters per squared second)
  acc_lim_theta: 0.7      #(in radians per squared second)

  holonomic_robot: false

  #Goal tolerance parameters
  yaw_goal_tolerance: 0.6
  xy_goal_tolerance: 0.3

  #dwa: true
  meter_scoring: true
