obstacle_range: 2.5       #Maximum distance (mts) that will be considered from sensor reading that will result in an obstacle put into the costmap.
raytrace_range: 3.0       #Maximum distance (mts) that will be considered when taking the free space around the robot and putting in the costmap.

max_obstacle_height: 0.4
min_obstacle_height: 0.05

footprint: [[0.36, -0.21], [0.36, 0.21], [-0.33, 0.21], [-0.33, -0.21]]
#robot_radius:
inflation_radius: 0.2

transform_tolerance: 1.0    #Set the tolerance we're willing to have for tf transforms

map_type: costmap


observation_sources: hokuyo_laser
hokuyo_laser: {sensor_frame: hokuyo_laser_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

#observation_sources: pointcloud_sensor
#pointcloud_sensor: {sensor_frame: camera_link, data_type: PointCloud2, topic: /camera/depth/points, marking: true, clearing: true}
