local_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  #transform_tolerance: 10
  update_frequency: 4.0
  publish_frequency: 3.0
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.1

#  plugins:
#   - {name: static_layer,        type: "costmap_2d::StaticLayer"}
#   - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}


#///////////////////////////////////////////////////////////////////////////////
